version: '3.8'

services:
  # Next.js Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sma-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-https://sma-aluminium.com}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST:-true}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/sma-data/uploads:/app/public/uploads
